document.addEventListener("DOMContentLoaded", async () => {
  const styles = document.createElement("style");
  styles.textContent = "@import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=Manrope:wght@600;700;800&family=Montserrat:wght@600;700;800&family=Playfair+Display:wght@600;700&family=Space+Grotesk:wght@600;700&family=Syne:wght@600;700;800&display=swap');.logo-ai-panel{margin-bottom:18px}.logo-ai-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;align-items:start}.logo-ai-grid .form-field{margin-top:12px}.logo-suggestions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.logo-suggestion{border:1px solid var(--admin-line);border-radius:10px;padding:12px;background:#fbfcfe;cursor:pointer}.logo-suggestion.selected{border:2px solid var(--admin-blue);background:#eef5ff}.logo-suggestion p{font-size:.82rem;color:var(--admin-muted);margin:7px 0}.logo-preview{min-height:150px;display:grid;place-items:center;gap:10px;border:1px dashed var(--admin-line);border-radius:10px;margin-top:16px;padding:16px}.logo-preview img{max-width:220px;max-height:150px;object-fit:contain}.logo-name-preview{font-size:2rem;font-weight:800;color:var(--admin-ink);margin-top:18px;text-align:center}.logo-ai-panel>.admin-btn{display:inline-flex;margin:12px 8px 0 0}.logo-ai-grid>div>.publish-logo{display:block;margin:12px 0 0}.logo-ai-panel form .admin-actions{margin-top:12px}.logo-ai-panel form .admin-btn{width:100%}@media(max-width:700px){.logo-ai-grid,.logo-suggestions{grid-template-columns:1fr}.logo-ai-panel>.admin-btn{width:100%;margin-right:0}}";
  document.head.appendChild(styles);
  const content = document.querySelector(".admin-content");
  const form = document.querySelector("#configForm");
  if (!content || !form) return;
  form.style.display = "none";
  const panel = document.createElement("div");
  panel.className = "admin-card logo-ai-panel";
  panel.innerHTML = `<h2>AI gợi ý và tải logo</h2><p class="stat-label">Nhập tên logo để Gemini đề xuất ý tưởng, hoặc tải ảnh trực tiếp từ máy tính. Ảnh PNG, JPG và WEBP sẽ được tự động làm nét.</p><div class="logo-ai-grid"><div><div class="form-field"><label>Tên logo</label><input id="aiLogoText" placeholder="Ví dụ: NovaPay"></div><div class="form-field"><label>Ký hiệu logo</label><input id="aiLogoMark" maxlength="3" placeholder="N"></div><div class="form-field"><label>Phong cách</label><input id="aiLogoStyle" placeholder="Premium, hiện đại, màu xanh"></div><div class="admin-actions"><button id="generateLogoIdeas" class="admin-btn" type="button">Tạo gợi ý bằng AI</button></div><div id="logoSuggestions" class="logo-suggestions"></div><button id="confirmLogoIdea" class="admin-btn" type="button" hidden>Xác nhận lựa chọn</button></div><div><form id="logoUploadForm"><div class="form-field"><label>Chọn logo từ máy tính</label><input name="logo" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" required></div><div class="admin-actions"><button class="admin-btn" type="submit">Tải lên và làm nét</button></div></form><form id="markUploadForm" style="margin-top:18px"><div class="form-field"><label>Tải ký hiệu logo từ máy tính</label><input name="mark" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" required></div><div class="admin-actions"><button class="admin-btn secondary" type="submit">Tải ký hiệu lên</button></div></form><div id="logoPreview" class="logo-preview"><span class="stat-label">Chưa có logo mới</span></div></div></div>`;
  content.insertBefore(panel, form);
  const fontField = document.createElement("div");
  fontField.className = "form-field full";
  fontField.innerHTML = `<label>Kiểu chữ tên logo</label><select name="logoFont"><option value="modern">1. Hiện đại</option><option value="elegant">2. Thanh lịch</option><option value="bold">3. Mạnh mẽ</option><option value="geometric">4. Hình học</option><option value="friendly">5. Thân thiện</option><option value="classic">6. Cổ điển</option><option value="clean">7. Sạch tối giản</option><option value="tech">8. Công nghệ</option><option value="luxury">9. Cao cấp</option><option value="playful">10. Vui tươi</option></select>`;
  const formActions = form.querySelector(".admin-actions");
  form.querySelector(".form-grid")?.appendChild(fontField);
  if (formActions) formActions.insertAdjacentHTML("beforebegin", `<p class="stat-label">Chọn một trong 10 kiểu chữ cho tên logo, sau đó bấm Lưu bản nháp.</p>`);
  fetch("/api/admin/branding", { credentials: "same-origin" }).then((response) => response.ok ? response.json() : null).then((result) => { if (result?.data?.logoFont) fontField.querySelector("select").value = result.data.logoFont; }).catch(() => {});
  const $ = (selector) => panel.querySelector(selector);
  const notify = (message, error = false) => { const toast = document.querySelector("#toast"); if (!toast) return; toast.textContent = message; toast.style.background = error ? "#a33b3b" : "#13243b"; toast.classList.add("show"); setTimeout(() => toast.classList.remove("show"), 2800); };
  let selected = null;
  const savedBranding = async () => { try { const response = await fetch("/api/admin/branding", { credentials: "same-origin" }); const result = await response.json(); return result.data || {}; } catch { return {}; } };
  const branding = await savedBranding();
  const initialBranding = { ...branding };
  const logoPreview = $("#logoPreview");
  const addAssetDeleteButton = (kind, label) => { const button = document.createElement("button"); button.type = "button"; button.className = "admin-btn danger"; button.textContent = label; button.addEventListener("click", async () => { if (!confirm(`${label}? Ảnh sẽ bị xóa khỏi bản nháp và website.`)) return; const response = await fetch(`/api/admin/logo/${kind}`, { method: "DELETE", credentials: "same-origin" }); if (!response.ok) return notify("Không thể xóa ảnh logo", true); const fieldName = kind === "mark" ? "logoMarkUrl" : "logoUrl"; const field = form.querySelector(`[name="${fieldName}"]`); if (field) field.value = ""; button.disabled = true; button.textContent = "Đã xóa"; logoPreview.innerHTML = "<span class=\"stat-label\">Không có ảnh đang sử dụng</span>"; notify("Đã xóa ảnh khỏi bản nháp và website"); }); panel.appendChild(button); };
  addAssetDeleteButton("logo", "Xóa logo đang dùng");
  addAssetDeleteButton("mark", "Xóa ký hiệu logo đang dùng");
  $("#aiLogoText").value = branding.logoText || "";
  $("#aiLogoMark").value = branding.logoMark || "";
  $("#aiLogoStyle").value = branding.logoFont || "modern";
  const fontOptions = ["modern", "elegant", "bold", "geometric", "friendly", "classic", "clean", "tech", "luxury", "playful"];
  const fontNames = ["Hiện đại", "Thanh lịch", "Mạnh mẽ", "Hình học", "Thân thiện", "Cổ điển", "Tối giản", "Công nghệ", "Cao cấp", "Vui tươi"];
  const fontSelect = document.createElement("select");
  fontSelect.id = "logoFontChoice";
  fontSelect.innerHTML = fontOptions.map((value, index) => `<option value="${value}">${index + 1}. ${fontNames[index]}</option>`).join("");
  fontSelect.value = branding.logoFont || "modern";
  const fontWrap = document.createElement("div");
  fontWrap.className = "form-field";
  fontWrap.innerHTML = "<label>10 kiểu chữ cho tên logo</label>";
  fontWrap.appendChild(fontSelect);
  panel.querySelector(".logo-ai-grid > div")?.appendChild(fontWrap);
  const fontFamilies = { modern: "Manrope", elegant: "Playfair Display", bold: "Montserrat", geometric: "Space Grotesk", friendly: "Manrope", classic: "DM Serif Display", clean: "Montserrat", tech: "Space Grotesk", luxury: "Playfair Display", playful: "Syne" };
  const namePreview = document.createElement("div");
  namePreview.className = "logo-name-preview";
  namePreview.textContent = $("#aiLogoText").value || "Tên logo của bạn";
  panel.querySelector(".logo-ai-grid > div")?.appendChild(namePreview);
  const applyPreview = () => { namePreview.textContent = $("#aiLogoText").value || "Tên logo của bạn"; namePreview.style.fontFamily = fontFamilies[fontSelect.value] || fontFamilies.modern; };
  fontSelect.addEventListener("change", applyPreview);
  applyPreview();
  const showSelectedFile = (input, label) => { input.addEventListener("change", () => { const file = input.files?.[0]; if (!file) return; const url = URL.createObjectURL(file); logoPreview.innerHTML = `<strong>${label}</strong><img src="${url}" alt="Xem trước ${label}"><span class="stat-label">Ảnh chỉ được lưu vào bản nháp sau khi tải lên.</span>`; }); };
  showSelectedFile(panel.querySelector('#logoUploadForm input[type="file"]'), "Xem trước logo");
  showSelectedFile(panel.querySelector('#markUploadForm input[type="file"]'), "Xem trước ký hiệu logo");
  if (branding.logoUrl || branding.logoMarkUrl) logoPreview.innerHTML = `<strong>Ảnh đang sử dụng</strong>${branding.logoUrl ? `<img src="${branding.logoUrl}" alt="Logo đang dùng">` : ""}${branding.logoMarkUrl ? `<img src="${branding.logoMarkUrl}" alt="Ký hiệu logo đang dùng">` : ""}`;
  const saveButton = document.createElement("button");
  saveButton.className = "admin-btn";
  saveButton.type = "button";
  saveButton.textContent = "Lưu thay đổi thương hiệu";
  panel.appendChild(saveButton);
  const restoreButton = document.createElement("button");
  restoreButton.className = "admin-btn secondary";
  restoreButton.type = "button";
  restoreButton.textContent = "Khôi phục thương hiệu ban đầu";
  panel.appendChild(restoreButton);
  restoreButton.addEventListener("click", () => { const setValue = (name, value) => { const input = form.querySelector(`[name="${name}"]`); if (input) input.value = value || ""; }; $("#aiLogoText").value = initialBranding.logoText || ""; $("#aiLogoMark").value = initialBranding.logoMark || ""; fontSelect.value = initialBranding.logoFont || "modern"; setValue("logoText", initialBranding.logoText); setValue("logoMark", initialBranding.logoMark); setValue("logoUrl", initialBranding.logoUrl); setValue("logoMarkUrl", initialBranding.logoMarkUrl); applyPreview(); $("#logoPreview").innerHTML = "<span class=\"stat-label\">Đã khôi phục logo ban đầu</span>"; notify("Đã khôi phục thương hiệu ban đầu"); });
  saveButton.addEventListener("click", () => {
    const setHidden = (name, value) => { let field = form.querySelector(`[name="${name}"]`); if (!field) { field = document.createElement("input"); field.type = "hidden"; field.name = name; form.appendChild(field); } field.value = value || ""; };
    setHidden("logoText", $("#aiLogoText").value);
    setHidden("logoMark", $("#aiLogoMark").value);
    setHidden("logoFont", fontSelect.value);
    form.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true }));
  });
  $("#generateLogoIdeas").addEventListener("click", async () => { const button = $("#generateLogoIdeas"); button.disabled = true; button.textContent = "Đang hỏi AI..."; try { const response = await fetch("/api/admin/logo/suggestions", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ logoText: $("#aiLogoText").value, logoMark: $("#aiLogoMark").value, style: $("#aiLogoStyle").value }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); const list = $("#logoSuggestions"); list.innerHTML = body.warning ? `<p class="stat-label">AI Gemini chưa phản hồi, đang hiển thị gợi ý dự phòng: ${body.warning}</p>` : ""; body.suggestions.forEach((idea, index) => { const card = document.createElement("article"); card.className = "logo-suggestion"; card.innerHTML = `<strong>${idea.name || `Ý tưởng ${index + 1}`}</strong><p>${idea.concept || idea.prompt || ""}</p><small>${(idea.colors || []).join(" · ")}</small>`; card.addEventListener("click", () => { panel.querySelectorAll(".logo-suggestion").forEach((item) => item.classList.remove("selected")); card.classList.add("selected"); selected = idea; $("#confirmLogoIdea").hidden = false; }); list.appendChild(card); }); } catch (error) { notify(error.message, true); } finally { button.disabled = false; button.textContent = "Tạo gợi ý bằng AI"; } });
  $("#confirmLogoIdea").addEventListener("click", async () => { if (!selected) return; const response = await fetch("/api/admin/logo/generate", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ logoText: $("#aiLogoText").value, logoMark: $("#aiLogoMark").value, colors: selected.colors || [] }) }); const body = await response.json(); if (!response.ok) return notify(body.error || "Không tạo được logo", true); form.querySelector('[name="logoText"]').value = body.logoText; form.querySelector('[name="logoMark"]').value = body.logoMark; form.querySelector('[name="logoUrl"]').value = body.url; $("#logoPreview").innerHTML = `<img src="${body.url}" alt="Logo AI đã tạo"><a href="${body.url}" download="logo.svg">Tải logo</a>`; notify("Đã tạo và chọn logo. Hãy bấm Lưu bản nháp."); });
  const addPublishButton = () => { let button = panel.querySelector(".publish-logo"); if (button) return button; button = document.createElement("button"); button.type = "button"; button.className = "admin-btn publish-logo"; button.textContent = "Đăng thay đổi lên website"; button.addEventListener("click", async () => { const response = await fetch("/api/admin/publish", { method: "POST", credentials: "same-origin" }); if (!response.ok) return notify("Không thể đăng thay đổi lên website", true); notify("Thay đổi logo đã được cập nhật lên website"); }); panel.querySelector("#logoPreview").after(button); return button; };
  $("#logoUploadForm").addEventListener("submit", async (event) => { event.preventDefault(); const response = await fetch("/api/admin/logo/upload", { method: "POST", credentials: "same-origin", body: new FormData(event.target) }); const body = await response.json(); if (!response.ok) return notify(body.error || "Tải logo thất bại", true); form.querySelector('[name="logoUrl"]').value = body.url; $("#logoPreview").innerHTML = `<img src="${body.url}" alt="Xem trước logo"><a href="${body.url}" download>Tải logo</a>`; addPublishButton(); notify(body.sharpened ? "Logo đã tải lên và làm nét." : "Logo SVG đã tải lên."); });
  $("#markUploadForm").addEventListener("submit", async (event) => { event.preventDefault(); const response = await fetch("/api/admin/logo/mark-upload", { method: "POST", credentials: "same-origin", body: new FormData(event.target) }); const body = await response.json(); if (!response.ok) return notify(body.error || "Tải ký hiệu thất bại", true); let markUrl = form.querySelector('[name="logoMarkUrl"]'); if (!markUrl) { markUrl = document.createElement("input"); markUrl.type = "hidden"; markUrl.name = "logoMarkUrl"; form.appendChild(markUrl); } markUrl.value = body.url; $("#logoPreview").innerHTML = `<img src="${body.url}" alt="Ký hiệu logo"><a href="${body.url}" download>Tải ký hiệu</a>`; addPublishButton(); notify(body.sharpened ? "Ký hiệu logo đã tải lên và làm nét." : "Ký hiệu SVG đã tải lên."); });
});
